### ISSUE TITLE
byReflection模式,Pb2Json::Json2Message转换不出repeated字段的数据

### ISSUE THREAD

**Issue by hyj0** [HaustWang/pb2json#1]
message Host {
    optional uint32 hash_id = 1; //存储hash
    optional string host = 2;  //监听地址
    optional uint32 port = 3;  //监听端口
}

message Config {
    repeated Host host = 1;
    optional uint32 self_hash_id = 2; // 本机存储hash
}

Pb2Json::Json2Message(json1, config1, true);  //todo:Pb2Json解析repeated丢失!!!  {"self_hash_id":1}   
    LOG_COUT << config1.host_size() << LOG_ENDL;
问题应该出在byReflection/pb2json.cpp:107行
int count = json.count(field->name());
改为
int count = json.size();
因为调用Json2RepeatedMessage之前已经取了一次value = json[field->name()],到Json2RepeatedMessage里面应该直接取json.size()了
因为没有测试完整的测试用例,所以不确定这样改是否完全对.

**Comment by HaustWang** [comment]
朋友你好，针对你的问题，我现在还是有点迷惑，你的意思是 {"self_hash_id":1}解析失败了还是说？

**Comment by HaustWang** [comment]
不是很理解你描述的是哪种情况，但却是其中有一个Bug，已经做了修复。

**Comment by hyj0** [comment]
我写了个测试代码
[https://github.com/hyj0/pb2json/commit/b98007de6cc511ab0f37f0885cc76238f1e5bc09](url)
最后输出的host_size是0, 应为3才是对的

**Comment by hyj0** [comment]
[https://github.com/hyj0/pb2json/commit/fff2b4e9ecbd9c0fd620f581fb1349cf4fdcc6b3](url)
这样改输出是3 应该是对的

**Comment by HaustWang** [comment]
感谢兄弟指出，问题已修复
